### ISSUE TITLE
Add warning to Depth mode when depth map is not generated

### ISSUE THREAD

**Issue by Mejval5** [NullTale/OutlineFilter#3]
Would be nice to have warning when the depth mode is used that you need to generate depth map in the URP settings
![image](https://github.com/NullTale/OutlineFilter/assets/48858230/d63fc538-dec2-4664-96b6-9ea6cb7addb3)

Cause without that the outline just doesn't work in the outline mode
![image](https://github.com/NullTale/OutlineFilter/assets/48858230/da64b15e-f81d-46bf-8987-d29607afd8d7)

**Comment by NullTale** [comment]
added ~
![image](https://github.com/NullTale/OutlineFilter/assets/1497430/6b61e822-d77c-41f1-8768-0eeaf92b5fa1)
